### ISSUE TITLE
Les variables d'environnement d'exemple ne sont pas à jour

### ISSUE THREAD

**Issue by sghribi** [lafranceinsoumise/oauth#7]
Le fichier [envfile.sample](https://github.com/lafranceinsoumise/oauth/blob/master/envfile.sample) n'est pas à jour, et ne suffit pas à démarrer facilement le serveur OAuth.

Il manque notamment :

``` bash
export SECRET_COOKIE=jesuisunsecreeet
export API_CLIENT_ID=oauth
export API_CLIENT_secret="incredible password"
```

Le endpoint n'est pas évident à deviner ; si on suppose que l'API tourne sur le port 8000, il faudrait que ça soit :

```bash
export API_ENDPOINT=http://localhost:8000/legacy/
```

Enfin quitte à mettre un serveur SMTP bidon, autant mettre celui utilisé dans [cette PR qui ajoute un container Docker Mailhog](https://github.com/lafranceinsoumise/api-django/pull/18)

```bash
export SMTP_URL=smtp://localhost:1025/
```

Je propose pas pour l'instant de PR, car je ne sais pas quels paramètres sont vraiment utiles :)

**Comment by jillro** [comment]
Effectivement, il est complètement obsolète ! Je vais le mettre à jour.
